### ISSUE TITLE
Special characters not properly replaced

### ISSUE THREAD

**Issue by gnuletik** [phihag/pdfform.js#6] opened 2018-02-26 04:11 UTC
For example; character `≤` is replaced with `"d`

**Comment by phihag** [comment] 2018-02-26 10:59
Thank you for the report. I can reproduce the problem with ≤ and will look into it. Of course, you are very welcome to contribute a patch.

**Comment by phihag** [comment] 2018-02-26 11:50
XFA seems unaffected, it's only a problem with AcroForms (i.e.: to reproduce, test with okular, evince, Chrome etc. , not Adobe Reader).

**Comment by phihag** [comment] 2018-03-08 00:40
With the new release 1.0.3, ≤ and other characters should be encoded correctly. However, it seems that okular - at least on my system - has trouble generating the appearances. If you click into the text input, however, everything works fine for me.

Can you confirm?

As always, patches (e.g. for appearance generation) welcome!

**Comment by gnuletik** [comment] 2018-03-08 05:08
Thanks @phihag for the fix !
I just updated the `pdf_js` version but got an error when using it
```
wget 'https://raw.githubusercontent.com/phihag/pdfform.js/dist/dist/pdfform.pdf_js.dist.js'
```

I got this in the browser console
```
TypeError: minipdf_lib.isNull is not a function
```

**Comment by phihag** [comment] 2018-03-08 05:18
Oh, I apologize. Should be fixed now.

**Comment by gnuletik** [comment] 2018-03-09 00:05
Hi @phihag,
Thanks for the fix abou `isNull`.
I also tried to generate a PDF file with `≤`.
It worked on Acrobat Reader but on Chrome it generate a space instead.

**Comment by phihag** [comment] 2018-03-09 09:33
I can reproduce this, but that seems to be a Chrome bug: I cannot manually input `≤` in an empty form with Chrome either. Can you?

**Closed by phihag** 2018-03-09 09:33 UTC
